name: TDS Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 22f2000058@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Finish
        run: echo "Done"
